{% set name = "DedupliPy" %}
{% set version = "0.7.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/DedupliPy-{{ version }}.tar.gz
  sha256: 55645fd733722ecddadb974de84db053be1e71149db3b58ea7fef70daf15976a

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - fancyimpute
    - modal
    - networkx
    - numpy
    - openpyxl
    - pandas
    - pyminhash
    - pytest
    - python-levenshtein
    - scikit-learn
    - scipy
    - thefuzz

test:
  imports:
    - deduplipy
    - deduplipy.active_learning
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fritshermans/deduplipy
  summary: End-to-end deduplication solution
  license: MIT
  license_file: LICENSE
  description: |
    <a href="https://deduplipy.readthedocs.io/en/latest/">
      <img src="https://deduplipy.readthedocs.io/en/latest/_images/logo.png" width="15%" height="15%" align="left" />
    </a>

    Deduplication is the task to combine different representations of the 
    same real world entity. This package implements deduplication using 
    active learning. Active learning allows for rapid training without 
    having to provide a large, manually labelled dataset.

    DedupliPy is an end-to-end solution with advantages over existing solutions:
    - active learning; no large manually labelled dataset required
    - during active learning, the user gets notified when the model 
      converged and training may be finished
    - works out of the box, advanced users can choose settings as 
      desired (custom blocking rules, custom metrics, interaction features)

    Developed by [Frits Hermans](https://www.linkedin.com/in/frits-hermans-data-scientist/)

    PyPI: [https://pypi.org/project/DedupliPy/](https://pypi.org/project/DedupliPy/)

  doc_url: https://deduplipy.readthedocs.io/en/latest/
  dev_url: https://github.com/fritshermans/deduplipy

extra:
  recipe-maintainers:
    - sugatoray
